-- Metadati invisibili usati dal motore per gerarchia e sostituzioni.
alter table public.exercises
  add column if not exists stability_profile text not null default 'free',
  add column if not exists axial_load smallint not null default 0,
  add column if not exists unilateral boolean not null default false;

alter table public.exercises
  drop constraint if exists exercises_stability_profile_valid,
  drop constraint if exists exercises_axial_load_valid;

alter table public.exercises
  add constraint exercises_stability_profile_valid
    check (stability_profile in ('supported', 'guided', 'free')),
  add constraint exercises_axial_load_valid check (axial_load between 0 and 3);

-- Correzioni del catalogo storico e backfill dei profili più importanti.
update public.exercises set movement_pattern = 'knee_extension' where id = 'leg_extension';
update public.exercises set movement_pattern = 'calf_raise' where id in ('calf_in_piedi', 'calf_libero', 'calf_manubri', 'calf_seduto');
update public.exercises set exercise_types = array['compound'], roles = array['compound', 'hypertrophy'] where id = 'trazioni_supine';
update public.exercises set exercise_types = array['compound'], roles = array['compound', 'hypertrophy'] where id = 'glute_bridge';
update public.exercises set stability_profile = 'guided' where equipment = 'machine';
update public.exercises set stability_profile = 'supported' where id in ('pulley', 'curl_panca_scott');
update public.exercises set axial_load = 3 where id in ('squat', 'front_squat', 'stacco', 'stacco_rumeno', 'military_press');
update public.exercises set axial_load = 2 where id in ('rematore_bil', 'goblet_squat', 'stacco_rumeno_man');
update public.exercises set unilateral = true where id in ('affondi_man', 'bulgarian_split', 'box_step_up', 'rematore_man');

with curated as (
  select * from jsonb_to_recordset($catalog$
  [
    {"id":"panca_piana_man","name":"Panca piana con manubri","english_name":"Dumbbell Bench Press","primary_muscles":["chest"],"secondary_muscles":["triceps","front_delts"],"equipment":"dumbbell","required_equipment":["dumbbells","bench"],"movement_pattern":"horizontal_push","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":2,"systemic_fatigue":3,"local_fatigue":3,"grip_fatigue":2,"default_sets":4,"default_reps":"8-12","default_rest":120,"stability_profile":"free","axial_load":0,"unilateral":false,"substitutions":["panca_piana","chest_press"]},
    {"id":"chest_press_inclinata","name":"Chest press inclinata","english_name":"Incline Chest Press","primary_muscles":["chest"],"secondary_muscles":["triceps","front_delts"],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"horizontal_push","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":2,"local_fatigue":3,"grip_fatigue":1,"default_sets":3,"default_reps":"8-12","default_rest":90,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["panca_inclinata_man","chest_press"]},
    {"id":"chest_press_convergente","name":"Chest press convergente","english_name":"Converging Chest Press","primary_muscles":["chest"],"secondary_muscles":["triceps","front_delts"],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"horizontal_push","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":2,"local_fatigue":3,"grip_fatigue":1,"default_sets":3,"default_reps":"8-12","default_rest":90,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["chest_press","panca_piana_man"]},
    {"id":"pec_deck","name":"Pec deck","english_name":"Pec Deck Fly","primary_muscles":["chest"],"secondary_muscles":[],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"chest_fly","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"12-15","default_rest":60,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["croci_cavi"]},
    {"id":"croci_manubri","name":"Croci con manubri","english_name":"Dumbbell Fly","primary_muscles":["chest"],"secondary_muscles":[],"equipment":"dumbbell","required_equipment":["dumbbells","bench"],"movement_pattern":"chest_fly","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"10-15","default_rest":75,"stability_profile":"supported","axial_load":0,"unilateral":false,"substitutions":["croci_cavi","pec_deck"]},

    {"id":"lat_machine_neutra","name":"Lat machine presa neutra","english_name":"Neutral-Grip Lat Pulldown","primary_muscles":["back"],"secondary_muscles":["biceps"],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"vertical_pull","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":2,"local_fatigue":3,"grip_fatigue":2,"default_sets":3,"default_reps":"8-12","default_rest":90,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["lat_machine","trazioni"]},
    {"id":"pulldown_unilaterale","name":"Pulldown unilaterale","english_name":"Single-Arm Lat Pulldown","primary_muscles":["back"],"secondary_muscles":["biceps"],"equipment":"cable","required_equipment":["cable"],"movement_pattern":"vertical_pull","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":2,"default_sets":3,"default_reps":"10-12 per lato","default_rest":75,"stability_profile":"supported","axial_load":0,"unilateral":true,"substitutions":["lat_machine_neutra","lat_machine"]},
    {"id":"rematore_chest_supported_man","name":"Rematore con manubri chest-supported","english_name":"Chest-Supported Dumbbell Row","primary_muscles":["back"],"secondary_muscles":["biceps","rear_delts"],"equipment":"dumbbell","required_equipment":["dumbbells","bench"],"movement_pattern":"horizontal_pull","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":3,"grip_fatigue":2,"default_sets":3,"default_reps":"8-12","default_rest":90,"stability_profile":"supported","axial_load":0,"unilateral":false,"substitutions":["t_bar_row","pulley"]},
    {"id":"t_bar_row","name":"T-Bar row","english_name":"T-Bar Row","primary_muscles":["back"],"secondary_muscles":["biceps","rear_delts"],"equipment":"barbell","required_equipment":["barbell"],"movement_pattern":"horizontal_pull","roles":["compound","strength","hypertrophy"],"exercise_types":["compound"],"min_experience":"intermediate","technical_complexity":2,"systemic_fatigue":3,"local_fatigue":3,"grip_fatigue":3,"default_sets":4,"default_reps":"6-10","default_rest":120,"stability_profile":"free","axial_load":2,"unilateral":false,"substitutions":["rematore_chest_supported_man","rematore_bil"]},
    {"id":"rematore_macchina","name":"Rematore alla macchina","english_name":"Machine Row","primary_muscles":["back"],"secondary_muscles":["biceps","rear_delts"],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"horizontal_pull","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":3,"grip_fatigue":2,"default_sets":3,"default_reps":"8-12","default_rest":90,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["rematore_chest_supported_man","pulley"]},
    {"id":"high_row_macchina","name":"High row alla macchina","english_name":"Machine High Row","primary_muscles":["back","rear_delts"],"secondary_muscles":["biceps"],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"horizontal_pull","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":3,"grip_fatigue":2,"default_sets":3,"default_reps":"10-12","default_rest":90,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["rematore_macchina","reverse_pec_deck"]},

    {"id":"landmine_press","name":"Landmine press","english_name":"Landmine Press","primary_muscles":["front_delts"],"secondary_muscles":["chest","triceps"],"equipment":"barbell","required_equipment":["barbell"],"movement_pattern":"vertical_push","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":2,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"8-12 per lato","default_rest":90,"stability_profile":"free","axial_load":1,"unilateral":true,"substitutions":["shoulder_press_man","shoulder_press_mac"]},
    {"id":"alzate_laterali_macchina","name":"Alzate laterali alla macchina","english_name":"Machine Lateral Raise","primary_muscles":["lateral_delts"],"secondary_muscles":[],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"lateral_raise","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"12-20","default_rest":45,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["alzate_laterali","alzate_laterali_cavo"]},
    {"id":"rear_delt_cavi","name":"Croci inverse ai cavi","english_name":"Cable Rear-Delt Fly","primary_muscles":["rear_delts"],"secondary_muscles":[],"equipment":"cable","required_equipment":["cable"],"movement_pattern":"rear_delt","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"12-20","default_rest":45,"stability_profile":"free","axial_load":0,"unilateral":false,"substitutions":["reverse_pec_deck","alzate_90"]},

    {"id":"pendulum_squat","name":"Pendulum squat","english_name":"Pendulum Squat","primary_muscles":["quads"],"secondary_muscles":["glutes"],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"squat","roles":["compound","strength","hypertrophy"],"exercise_types":["compound"],"min_experience":"intermediate","technical_complexity":2,"systemic_fatigue":3,"local_fatigue":3,"grip_fatigue":1,"default_sets":4,"default_reps":"6-10","default_rest":150,"stability_profile":"guided","axial_load":2,"unilateral":false,"substitutions":["hack_squat","belt_squat","leg_press"]},
    {"id":"reverse_lunge_man","name":"Affondo inverso con manubri","english_name":"Dumbbell Reverse Lunge","primary_muscles":["quads","glutes"],"secondary_muscles":["hamstrings"],"equipment":"dumbbell","required_equipment":["dumbbells"],"movement_pattern":"lunge","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":2,"systemic_fatigue":2,"local_fatigue":3,"grip_fatigue":2,"default_sets":3,"default_reps":"8-12 per gamba","default_rest":90,"stability_profile":"free","axial_load":1,"unilateral":true,"substitutions":["affondi_man","bulgarian_split"]},
    {"id":"single_leg_rdl","name":"Stacco rumeno a una gamba","english_name":"Single-Leg Romanian Deadlift","primary_muscles":["hamstrings"],"secondary_muscles":["glutes","core"],"equipment":"dumbbell","required_equipment":["dumbbells"],"movement_pattern":"hinge","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"intermediate","technical_complexity":2,"systemic_fatigue":2,"local_fatigue":3,"grip_fatigue":2,"default_sets":3,"default_reps":"8-12 per gamba","default_rest":90,"stability_profile":"free","axial_load":1,"unilateral":true,"substitutions":["stacco_rumeno_man","stacco_rumeno"]},
    {"id":"good_morning_bil","name":"Good morning con bilanciere","english_name":"Barbell Good Morning","primary_muscles":["hamstrings"],"secondary_muscles":["glutes","back"],"equipment":"barbell","required_equipment":["barbell"],"movement_pattern":"hinge","roles":["compound","strength","hypertrophy"],"exercise_types":["compound"],"min_experience":"advanced","technical_complexity":3,"systemic_fatigue":3,"local_fatigue":3,"grip_fatigue":1,"default_sets":3,"default_reps":"6-10","default_rest":150,"stability_profile":"free","axial_load":3,"unilateral":false,"substitutions":["stacco_rumeno","stacco_rumeno_man"]},
    {"id":"leg_curl_seduto","name":"Leg curl seduto","english_name":"Seated Leg Curl","primary_muscles":["hamstrings"],"secondary_muscles":[],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"knee_flexion","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"10-15","default_rest":60,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["leg_curl"]},
    {"id":"leg_extension_unilaterale","name":"Leg extension unilaterale","english_name":"Single-Leg Extension","primary_muscles":["quads"],"secondary_muscles":[],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"knee_extension","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"12-15 per gamba","default_rest":45,"stability_profile":"guided","axial_load":0,"unilateral":true,"substitutions":["leg_extension"]},
    {"id":"hip_thrust_macchina","name":"Hip thrust alla macchina","english_name":"Machine Hip Thrust","primary_muscles":["glutes"],"secondary_muscles":["hamstrings"],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"hinge","roles":["compound","hypertrophy"],"exercise_types":["compound"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":2,"local_fatigue":3,"grip_fatigue":1,"default_sets":3,"default_reps":"8-12","default_rest":90,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["hip_thrust","glute_bridge"]},
    {"id":"glute_kickback_cavo","name":"Glute kickback al cavo","english_name":"Cable Glute Kickback","primary_muscles":["glutes"],"secondary_muscles":[],"equipment":"cable","required_equipment":["cable"],"movement_pattern":"hip_extension","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"12-20 per gamba","default_rest":45,"stability_profile":"supported","axial_load":0,"unilateral":true,"substitutions":["abduzioni_macchina","hip_thrust_macchina"]},
    {"id":"calf_leg_press","name":"Calf raise alla leg press","english_name":"Leg Press Calf Raise","primary_muscles":["calves"],"secondary_muscles":[],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"calf_raise","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":4,"default_reps":"12-20","default_rest":45,"stability_profile":"guided","axial_load":0,"unilateral":false,"substitutions":["calf_in_piedi","calf_seduto"]},

    {"id":"curl_inclinata_man","name":"Curl con manubri su panca inclinata","english_name":"Incline Dumbbell Curl","primary_muscles":["biceps"],"secondary_muscles":[],"equipment":"dumbbell","required_equipment":["dumbbells","bench"],"movement_pattern":"elbow_flexion","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":2,"default_sets":3,"default_reps":"8-12","default_rest":60,"stability_profile":"supported","axial_load":0,"unilateral":false,"substitutions":["curl_manubri","curl_cavo"]},
    {"id":"bayesian_curl","name":"Bayesian curl al cavo","english_name":"Bayesian Cable Curl","primary_muscles":["biceps"],"secondary_muscles":[],"equipment":"cable","required_equipment":["cable"],"movement_pattern":"elbow_flexion","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"10-15 per lato","default_rest":45,"stability_profile":"free","axial_load":0,"unilateral":true,"substitutions":["curl_cavo","curl_inclinata_man"]},
    {"id":"preacher_curl_macchina","name":"Preacher curl alla macchina","english_name":"Machine Preacher Curl","primary_muscles":["biceps"],"secondary_muscles":[],"equipment":"machine","required_equipment":["machines"],"movement_pattern":"elbow_flexion","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"8-12","default_rest":60,"stability_profile":"supported","axial_load":0,"unilateral":false,"substitutions":["curl_panca_scott","curl_cavo"]},
    {"id":"pushdown_unilaterale","name":"Pushdown unilaterale","english_name":"Single-Arm Cable Pushdown","primary_muscles":["triceps"],"secondary_muscles":[],"equipment":"cable","required_equipment":["cable"],"movement_pattern":"elbow_extension","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"10-15 per lato","default_rest":45,"stability_profile":"free","axial_load":0,"unilateral":true,"substitutions":["pushdown","estensioni_sopra_testa"]},
    {"id":"estensione_tricipiti_cavo_alto","name":"Estensione tricipiti sopra la testa al cavo","english_name":"Overhead Cable Triceps Extension","primary_muscles":["triceps"],"secondary_muscles":[],"equipment":"cable","required_equipment":["cable"],"movement_pattern":"elbow_extension","roles":["isolation","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"10-15","default_rest":60,"stability_profile":"free","axial_load":0,"unilateral":false,"substitutions":["estensioni_sopra_testa","french_press"]},

    {"id":"ab_wheel","name":"Ab wheel rollout","english_name":"Ab Wheel Rollout","primary_muscles":["core"],"secondary_muscles":[],"equipment":"bodyweight","required_equipment":[],"movement_pattern":"core","roles":["compound","core","hypertrophy"],"exercise_types":["compound"],"min_experience":"intermediate","technical_complexity":2,"systemic_fatigue":2,"local_fatigue":3,"grip_fatigue":1,"default_sets":3,"default_reps":"8-15","default_rest":60,"stability_profile":"free","axial_load":0,"unilateral":false,"substitutions":["plank","crunch_cavo"]},
    {"id":"pallof_press","name":"Pallof press","english_name":"Pallof Press","primary_muscles":["core"],"secondary_muscles":[],"equipment":"cable","required_equipment":["cable"],"movement_pattern":"core","roles":["isolation","core","hypertrophy"],"exercise_types":["isolation"],"min_experience":"beginner","technical_complexity":1,"systemic_fatigue":1,"local_fatigue":2,"grip_fatigue":1,"default_sets":3,"default_reps":"10-15 per lato","default_rest":45,"stability_profile":"free","axial_load":0,"unilateral":true,"substitutions":["crunch_cavo","plank"]}
  ]
  $catalog$::jsonb) as x(
    id text, name text, english_name text, primary_muscles text[], secondary_muscles text[],
    equipment text, required_equipment text[], movement_pattern text, roles text[], exercise_types text[],
    min_experience text, technical_complexity smallint, systemic_fatigue smallint, local_fatigue smallint,
    grip_fatigue smallint, default_sets smallint, default_reps text, default_rest smallint,
    stability_profile text, axial_load smallint, unilateral boolean, substitutions text[]
  )
)
insert into public.exercises (
  id, name, english_name, primary_muscles, secondary_muscles, equipment, required_equipment,
  movement_pattern, roles, exercise_types, workout_roles, min_experience, technical_complexity,
  systemic_fatigue, local_fatigue, grip_fatigue, cardio_demand, default_sets, default_reps,
  default_rest, instructions, description, category, metcon_safe, warmup_relevant,
  substitutions, stability_profile, axial_load, unilateral, active
)
select
  id, name, english_name, primary_muscles, secondary_muscles, equipment, required_equipment,
  movement_pattern, roles, exercise_types, array['hypertrophy']::text[], min_experience,
  technical_complexity, systemic_fatigue, local_fatigue, grip_fatigue, 1, default_sets,
  default_reps, default_rest,
  'Mantieni una tecnica controllata, usa un range di movimento senza dolore e interrompi la serie prima che la forma peggiori.',
  name || ': variante selezionata per traiettoria, supporto o attrezzatura distinti.',
  equipment, false, false, substitutions, stability_profile, axial_load, unilateral, true
from curated
on conflict (id) do update set
  name = excluded.name,
  english_name = excluded.english_name,
  primary_muscles = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  equipment = excluded.equipment,
  required_equipment = excluded.required_equipment,
  movement_pattern = excluded.movement_pattern,
  roles = excluded.roles,
  exercise_types = excluded.exercise_types,
  substitutions = excluded.substitutions,
  stability_profile = excluded.stability_profile,
  axial_load = excluded.axial_load,
  unilateral = excluded.unilateral,
  active = true;

create index if not exists exercises_replacement_profile_idx
  on public.exercises (movement_pattern, stability_profile, unilateral)
  where active = true;
